# Generated by Django 3.1 on 2020-08-13 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0003_auto_20200812_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_invited_person',
            field=models.BooleanField(default=False, verbose_name='Invited Person?'),
        ),
    ]
