# Generated by Django 3.1 on 2020-08-13 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_startup_original_id'),
        ('customuser', '0005_auto_20200813_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rated',
            name='startup',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.startup'),
        ),
    ]
