# Generated by Django 3.1 on 2020-08-13 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_startup_original_id'),
        ('customuser', '0006_auto_20200813_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rated',
            name='achievements_bar',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rated',
            name='business_bar',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rated',
            name='market_bar',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rated',
            name='product_bar',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rated',
            name='startup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.startup'),
        ),
        migrations.AlterField(
            model_name='rated',
            name='team_bar',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rated',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
