# Generated by Django 3.1 on 2020-08-13 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0007_auto_20200813_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rated',
            name='achievements_bar',
        ),
        migrations.RemoveField(
            model_name='rated',
            name='business_bar',
        ),
        migrations.RemoveField(
            model_name='rated',
            name='market_bar',
        ),
        migrations.RemoveField(
            model_name='rated',
            name='product_bar',
        ),
        migrations.RemoveField(
            model_name='rated',
            name='team_bar',
        ),
    ]
