# Generated by Django 3.1 on 2020-08-12 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Startups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(max_length=32)),
                ('approved', models.CharField(max_length=3)),
                ('contest', models.CharField(max_length=250)),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('position', models.CharField(max_length=250)),
                ('company', models.CharField(max_length=250)),
                ('website', models.CharField(max_length=250)),
                ('linkedin', models.CharField(max_length=250)),
                ('facebook', models.CharField(max_length=250)),
                ('employees', models.CharField(max_length=250)),
                ('stage', models.CharField(max_length=250)),
                ('funding', models.CharField(max_length=250)),
                ('video', models.CharField(max_length=250)),
                ('idea', models.TextField()),
                ('logo', models.CharField(max_length=250)),
                ('presentation', models.CharField(max_length=250)),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'startups',
                'managed': False,
            },
        ),
    ]
