# Generated by Django 3.1 on 2020-08-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_startup_original_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='achievements_bar',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='startup',
            name='business_bar',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='startup',
            name='market_bar',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='startup',
            name='product_bar',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='startup',
            name='team_bar',
            field=models.IntegerField(default=0),
        ),
    ]
