# Generated by Django 3.1 on 2020-08-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20200813_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage1', models.BooleanField(default=True)),
                ('stage2', models.BooleanField(default=False)),
            ],
        ),
    ]
