# Generated by Django 3.1 on 2020-08-14 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='presentation_bar',
            field=models.IntegerField(default=0),
        ),
    ]
